Add V
Comamoca/Awesome-DDSK pull request #45
Opened 2024-09-17 13:14 UTC by syobocat

V言語で実装してみました

Dockerfileの動作は未検証です

2024-09-17 15:34 UTC, Comamoca requested changes
PRありがとうございます！
レビューに一つコメントをしたので確認して修正していただけると幸いです。

2024-09-17 15:34 UTC, Comamoca commented on V/Dockerfile
Dockerfileをマルチステージビルドにするとコンテナサイズを削減できるので、もし可能ならお願いします。

https://matsuand.github.io/docs.docker.jp.onthefly/develop/develop-images/multistage-build/

2024-09-18 02:01 UTC, syobocat commented on V/Dockerfile
マルチステージビルドに変更しました。同時に動作確認も行いました。

2024-09-20 19:34 UTC, Comamoca approved these changes
修正ありがとうございます！
確認が出来ましたのでmergeさせていただきます。

2024-09-20 19:34 UTC, merged